"""Hashtag blending engine — mixes LLM tags with curated viral pools per platform."""

import logging

log = logging.getLogger(__name__)

_PLATFORM_CAPS = {"instagram": 5, "tiktok": 5, "youtube": 5}
_DEFAULT_CAP = 5

# Research-validated pools (June 2026). IG cap = 5 tags; quality > quantity.
# Category/content tags are generated by LLM — pools provide reach/format signal.
_DEFAULT_POOLS = {
    # Strategy: 1 reach + 1 format + rotate niche. 5-tag cap per Mosseri (2026).
    "instagram": [
        "travelreels", "reelsviral", "explorepage", "reelstravel",
        "hiddengem", "budgettravel", "solotravel", "adventuretravel",
        "offthebeatenpath", "travelinspiration", "traveltips",
        "culturaltravel", "foodtravel", "beachvibes",
    ],
    # TikTok: 3-5 tags; mid-size (<5M) beat #fyp stacking.
    "tiktok": [
        "TravelTok", "HiddenGem", "TravelTips", "BudgetTravel",
        "TravelDiaries", "SoloTravel", "TikTokTravel", "fyp",
    ],
    # YouTube Shorts: title/description SEO > hashtags; 3-5 max.
    "youtube": [
        "Shorts", "TravelShorts", "TravelTips", "HiddenGem", "TravelGuide",
    ],
}


def blend(
    llm_tags: list[str],
    platform: str,
    category: str | None = None,
    post_seq: int = 0,
) -> list[str]:
    """Blend LLM-generated hashtags with curated viral pool tags for the given platform.

    Args:
        llm_tags: LLM-generated hashtags_en list (already chosen variant by caller).
        platform: One of "instagram", "tiktok", "youtube".
        category: Optional category hint (reserved for future pool segmentation).
        post_seq: Post sequence number used to rotate curated picks so every post differs.

    Returns:
        Merged, deduplicated, denylist-filtered, platform-capped list of hashtag strings.
    """
    try:
        from backend.api.routes.settings import get_setting  # avoid circular at module level
        cfg_hashtags = get_setting("hashtags") or {}
    except Exception as exc:
        log.warning("hashtag_engine: could not read settings (%s), using defaults", exc)
        cfg_hashtags = {}

    curated_enabled = cfg_hashtags.get("curated_enabled", True)
    blend_count = int(cfg_hashtags.get("blend_count", 3))
    pools_cfg = cfg_hashtags.get("pools") or {}
    cap = _PLATFORM_CAPS.get(platform, _DEFAULT_CAP)

    # Build blocked set — reuse caption_gen's policy so both are in sync.
    try:
        from backend.pipeline.caption_gen import _DEFAULT_BLOCKED_TAGS, _dedupe_filter
    except Exception as exc:
        log.warning("hashtag_engine: could not import caption_gen helpers (%s), using empty blocked set", exc)
        _DEFAULT_BLOCKED_TAGS = set()  # type: ignore[assignment]

        def _dedupe_filter(tags: list, blocked: set) -> list:  # type: ignore[misc]
            seen: set[str] = set()
            out: list[str] = []
            for t in tags:
                if not isinstance(t, str):
                    continue
                norm = t.strip().lstrip("#")
                low = norm.lower()
                if not norm or low in blocked or low in seen:
                    continue
                seen.add(low)
                out.append(norm)
            return out

    configured_blocked = cfg_hashtags.get("blocked") or []
    blocked: set[str] = (
        {t.lower().lstrip("#") for t in configured_blocked}
        if configured_blocked
        else _DEFAULT_BLOCKED_TAGS
    )

    if not curated_enabled:
        return _dedupe_filter(llm_tags, blocked)[:cap]

    # Resolve pool: prefer user-configured pool if non-empty, else code default.
    platform_key = platform.lower()
    user_pool: list[str] = pools_cfg.get(platform_key) or []
    pool: list[str] = user_pool if user_pool else _DEFAULT_POOLS.get(platform_key, [])

    curated_picks: list[str] = []
    if pool:
        pool_len = len(pool)
        start = post_seq % pool_len
        # Wrap around if needed.
        indices = [(start + i) % pool_len for i in range(min(blend_count, pool_len))]
        curated_picks = [pool[i] for i in indices]

    # Merge: curated first so they land in the final set, then LLM tags.
    merged = curated_picks + list(llm_tags)
    filtered = _dedupe_filter(merged, blocked)
    return filtered[:cap]
