import type { ElementType } from "react";
import {
  Clock, Brain, MessageCircle, Music2, Tag, Layers,
  BarChart3, Sliders, Sparkles, Hash, Eye, Target, Film, AtSign, HardDrive,
  Clapperboard, PlayCircle, DollarSign, Scissors, Eraser, Video, Mic,
} from "lucide-react";
import type { FieldHint } from "./types";

export const FIELD_HINTS: Record<string, FieldHint> = {
  // approval — per-platform auto-post gates
  "approval.instagram_auto_enabled": { desc: "Auto-publish to Instagram when the window elapses. Disable to require manual approval for Instagram.", recommended: "true" },
  "approval.instagram_auto_minutes": { desc: "Minutes after creation before the daemon auto-publishes to Instagram.", example: "60", recommended: "60" },
  "approval.tiktok_auto_enabled": { desc: "Auto-publish to TikTok when the window elapses. Disable to require manual approval for TikTok.", recommended: "false" },
  "approval.tiktok_auto_minutes": { desc: "Minutes after creation before the daemon auto-publishes to TikTok.", example: "60", recommended: "60" },
  "approval.youtube_auto_enabled": { desc: "Auto-publish to YouTube when the window elapses. Disable to require manual approval for YouTube.", recommended: "false" },
  "approval.youtube_auto_minutes": { desc: "Minutes after creation before the daemon auto-publishes to YouTube.", example: "60", recommended: "60" },
  "approval.require_manual_for_categories": { desc: "Categories that always require manual approval even when auto-post is on.", example: "hidden_gem, beach", recommended: "(empty)" },
  // schedule
  "schedule.daily_slots": { desc: "UTC times when the scheduler will publish posts each day.", example: "09:00, 13:00, 19:00", recommended: "09:00, 13:00, 19:00" },
  "schedule.timezone": { desc: "IANA timezone used for slot display and scheduling logic.", example: "Asia/Beirut", recommended: "your local timezone" },
  "schedule.max_per_day": { desc: "Hard cap on posts published per calendar day.", example: "3", recommended: "3" },
  "schedule.optimize_times": { desc: "Order free daily slots by historical engagement so the best-performing time gets filled first (Enh C).", recommended: "true" },
  // platforms
  "platforms.instagram_enabled": { desc: "Publish to Instagram via Graph API when enabled.", recommended: "true" },
  "platforms.youtube_enabled": { desc: "Upload as YouTube Short when enabled. Requires YOUTUBE_CLIENT_SECRET + YOUTUBE_REFRESH_TOKEN in .env.", recommended: "false (until OAuth configured)" },
  "platforms.tiktok_enabled": { desc: "Post to TikTok via Direct Post API. Requires TIKTOK_CLIENT_SECRET + TIKTOK_ACCESS_TOKEN in .env.", recommended: "false (until OAuth configured)" },
  // color — content-aware LUT (colour grade) selection
  "color.lut_mode": { desc: "How the colour grade LUT is chosen per clip. category = by content category; mood = by caption mood; vision = AI picks from the frames; fixed = always one LUT.", example: "category", recommended: "category" },
  "color.fixed_lut": { desc: "The single LUT applied to every reel when mode = fixed.", recommended: "(pick a cinematic LUT)" },
  "color.use_vision": { desc: "Allow AI-vision to override the LUT pick by looking at the frames. Adds a Groq call per edit; ignored in fixed mode.", recommended: "false" },
  "color.intensity": { desc: "Advisory grade strength — the full LUT is applied for now (no opacity blend yet).", example: "100%", recommended: "100%" },
  // ai
  "ai.classifier_model": { desc: "Groq model used to tag category + tags from captions.", example: "groq/llama-3.3-70b", recommended: "groq/llama-3.3-70b" },
  "ai.caption_model": { desc: "OpenRouter model used to generate EN + AR captions.", example: "openai/gpt-oss-20b:free", recommended: "openai/gpt-oss-20b:free" },
  "ai.refine_model": { desc: "OpenRouter model used to refine existing captions on request.", example: "openai/gpt-oss-20b:free", recommended: "openai/gpt-oss-20b:free" },
  // telegram
  "telegram.mode": { desc: "poll = bot pulls updates (dev). webhook = Telegram pushes updates (prod, faster).", example: "poll", recommended: "webhook (prod) / poll (dev)" },
  "telegram.chat_id": { desc: "Telegram chat ID that receives previews and pipeline notifications.", example: "-1001234567890" },
  "telegram.preview_push_enabled": { desc: "Send a preview message with Approve/Reject buttons when a post is created.", recommended: "true" },
  "telegram.always_preview": {
    desc: "Push a rich preview to Telegram at creation even when auto-publish is on — lets you cancel/reschedule before the slot.",
    recommended: "true",
  },
  "telegram.rich_publish_notify": {
    desc: "Post-publish Telegram notification includes media details, caption excerpt, and a Watch link instead of just the platform ID.",
    recommended: "true",
  },
  "telegram.admin_controls": {
    desc: "Show extended admin buttons on every preview (Edit caption, Details, Reschedule menu, Regenerate). Disable for a minimal approve/reject-only UI.",
    recommended: "true",
  },
  // music
  "music.preferred_source": { desc: "licensed = use local assets/music tracks. pixabay = search Pixabay API.", example: "licensed", recommended: "licensed" },
  "music.pixabay_query": { desc: "Search query sent to Pixabay when preferred_source is pixabay.", example: "travel cinematic", recommended: "travel cinematic" },
  "music.swap_on_detect_original": { desc: "Auto-replace audio if the original IG soundtrack is detected (avoids copyright strikes).", recommended: "true" },
  "music.mood_match": { desc: "Pick background music whose mood matches the caption tone instead of a fixed query (Enh G).", recommended: "true" },
  "music.favourite_boost": { desc: "Score bonus added to tracks favourited in the Audio Management page, so they get picked more often.", example: "3.0", recommended: "3.0" },
  "music.usage_weight": { desc: "Score bonus scale applied per historical use (log-scaled) — rewards proven tracks without letting one track dominate every reel.", example: "0.3", recommended: "0.3" },
  "music.cooldown_recent_cap": { desc: "How many recently-used tracks are remembered for no-repeat cooldown when auto-picking music.", example: "10", recommended: "10" },
  // caption (Enh A/B/J/L)
  "caption.use_feedback": { desc: "Inject the top-performing past hooks into the caption generator so new captions echo what already worked (Enh A).", recommended: "true" },
  "caption.use_trends": { desc: "Inject the current weekly Google-Trends travel topics into caption generation for timeliness (Enh B).", recommended: "true" },
  "caption.self_critique": { desc: "Run an extra Haiku pass that rewrites only the hook line for stronger scroll-stopping power (Enh J).", recommended: "true" },
  "caption.draft_with_groq": { desc: "Draft the caption on the free Groq tier, then let the Haiku self-critique pass polish it — drives caption cost toward $0 (Enh L). Keep self-critique on for best quality.", recommended: "false (quality) / true (cost savings)" },
  // caption — new keys (use_hook_library, trends_geo, hook_templates)
  "caption.use_hook_library": { desc: "Inject curated viral hook templates into the caption prompt to inspire stronger opening lines.", recommended: "true" },
  "caption.trends_geo": { desc: "Geo-target Google Trends to the clip's location for more relevant trending topics.", recommended: "true" },
  "caption.hook_templates": { desc: "Custom hook template strings. Empty = use built-in library (recommended).", example: '["POV: you just found...", "Nobody talks about..."]' },
  // hashtags (Enh D/L)
  "hashtags.ab_test": { desc: "Per post, coin-flip between the primary hashtag set and an alternate variant to A/B test reach (Enh D). Report under Analytics → Hashtags.", recommended: "true" },
  "hashtags.blocked": { desc: "Over-saturated / shadow-ban-prone tags stripped from every generated hashtag set. Leave empty to use the built-in default denylist (Enh L).", example: "travel, instagood, photography", recommended: "(empty — use built-in denylist)" },
  // hashtags — new keys (curated_enabled, blend_count, pools)
  "hashtags.curated_enabled": { desc: "Blend curated viral hashtag pools with LLM-generated tags for better reach.", recommended: "true" },
  "hashtags.blend_count": { desc: "How many curated pool tags to inject per post (rotated to vary each post).", recommended: "8" },
  "hashtags.pools": { desc: "Per-platform curated hashtag pools (Instagram/TikTok/YouTube). Empty lists = use built-in pools.", example: '{"instagram":["reelsviral","explorepage"],"tiktok":["traveltok","fyp"],"youtube":["TravelVlog"]}' },
  // monetize (new group)
  "monetize.enabled": { desc: "Append a CTA line to post captions on selected platforms." },
  "monetize.cta_text": { desc: "Call-to-action text appended to caption body.", example: '"Full guide & links in bio 🔗"' },
  "monetize.youtube_link": { desc: "Clickable link appended to YouTube description only (after CTA text).", example: '"https://yourlink.com"' },
  "monetize.platforms": { desc: "Which platforms receive the CTA injection.", example: '["instagram","tiktok","youtube"]' },
  // vision (Enh E)
  "vision.enabled": { desc: "Run the vision hook-scoring stage (Groq vision, local Moondream/Ollama fallback) to rate each video's opening frames (Enh E).", recommended: "true" },
  // selection (Enh I)
  "selection.use_performance": { desc: "Blend each category's realized engagement into clip selection so proven categories get picked more often (Enh I).", recommended: "true" },
  "selection.performance_weight": { desc: "How hard proven categories lift a clip's hook score during selection. 0 = ignore performance, 1 = maximum lift.", example: "0.5", recommended: "0.5" },
  "selection.min_duration_s": { desc: "Reject clips shorter than this many seconds at selection time. Reels need length to land.", example: "10", recommended: "10" },
  "selection.min_short_side": { desc: "Reject clips whose shortest edge (px) is below this resolution. 0 = off. Null-safe: clips with unknown dimensions are never rejected.", example: "720", recommended: "720" },
  "selection.min_hook_score": { desc: "Reject clips with a predicted hook score below this. 0 = off (safe for archives where hook scores aren't filled in yet).", example: "0", recommended: "0 (calibrate from real scores first)" },
  "selection.require_video_only": { desc: "Only ever pick VIDEO media — images/carousels can't be published as Reels/Shorts.", recommended: "true" },
  "selection.quality_probe_enabled": { desc: "Run the FFmpeg blur/shake probe as the first pipeline stage when creating a reel (0.6.0).", recommended: "true" },
  "selection.min_quality_score": { desc: "Reject clips whose blur/shake quality score (0–1) is below this. 0 = measure-only: scores are stored but nothing is rejected, so you can calibrate a threshold first.", example: "0", recommended: "0 (measure first, then enforce)" },
  "selection.require_classified": { desc: "Only pick clips that have category, hook_score, and tags all set. Falls back to the full pool if no fully-classified clips are available, so the queue never starves during vision backfill.", recommended: "true" },
  "selection.category_cooldown_categories": { desc: "Skip a category until this many OTHER distinct categories have been posted since — applies to the 'diverse' single-clip strategy and merge auto-category pick. \"Unknown\" is always excluded from auto-pick regardless of this setting. 0 = off. Falls back to the full pool when all categories are in cooldown.", example: "20", recommended: "20-30" },
  // taxonomy
  "taxonomy.categories": { desc: "Allowed content category slugs. The classifier picks from this list.", example: "hidden_gem, budget, culture", recommended: "hidden_gem, budget, culture, nature, food, beach" },
  // analytics
  "analytics.ingest_interval_hours": { desc: "How often (hours) to pull fresh stats from the Instagram API.", example: "6", recommended: "6" },
  // pipeline
  "pipeline.auto_publish_enabled": { desc: "Master kill-switch for the publish daemon. Off = queue builds up, nothing posts.", recommended: "true" },
  "pipeline.auto_create_enabled": { desc: "Daemon auto-picks a raw clip at each daily slot and runs the full pipeline. Off = manual creation only.", recommended: "true" },
  "pipeline.auto_create_mode": { desc: "approval = Telegram preview pushed, you approve before posting. publish = post auto-published at slot time with no human gate.", example: "approval", recommended: "approval (safer)" },
  "pipeline.auto_create_strategy": { desc: "How the next clip is picked: best = highest hook score. random = random unposted clip. diverse = random pick across all categories with cooldown to avoid repeating the same category.", example: "diverse", recommended: "diverse (best variety)" },
  "pipeline.auto_create_category": { desc: "Restrict auto-create to a specific category. Leave empty to pick from any category.", example: "culture", recommended: "(empty — all categories)" },
  "pipeline.auto_create_reel_type": { desc: "Which pipeline the daemon runs at each slot: merge = multi-clip cinematic montage (randomly picks a category, weighted by footage, when auto_create_category is empty — same cooldown as diverse, so it won't repeat a just-used category). single = one clip, picked by auto_create_strategy. Saving \"merge\" here also turns on merge.enabled.", example: "merge", recommended: "merge" },
  "pipeline.index_enabled": { desc: "Run the index stage (scan local archive for new media).", recommended: "true" },
  "pipeline.classify_enabled": { desc: "Run the classifier stage (Groq category + tags tagger).", recommended: "true" },
  "pipeline.resize_enabled": { desc: "Run the resize stage (FFmpeg 9:16 crop to 1080×1920).", recommended: "true" },
  "pipeline.enhance_enabled": { desc: "Run the enhance stage (stabilize, color grade, sharpen, normalize audio, watermark blur).", recommended: "true" },
  "pipeline.caption_enabled": { desc: "Run caption generation (Claude EN + AR captions).", recommended: "true" },
  "pipeline.upload_enabled": { desc: "Upload finished reels to R2 before publishing.", recommended: "true" },
  // platforms — youtube playlists (nested under platforms.youtube, group stays "platforms")
  "platforms.playlists_enabled": { desc: "Auto-group published YouTube Shorts into per-category YouTube playlists. Requires full youtube OAuth scope (re-run auth_youtube.py).", recommended: "true (if YouTube enabled)" },
  // storage / disk management
  "storage.reels_max_gb": { desc: "Hard cap on local reels_ready disk usage in GB. Oldest uploaded/orphaned files are deleted automatically to stay under this limit.", example: "5", recommended: "5" },
  "storage.reels_min_age_days": { desc: "Files newer than this many days are never auto-deleted, even if the disk cap is exceeded. Protects recently created reels still in the pipeline.", example: "7", recommended: "7" },
  // branding overlay (v0.7.0)
  "branding.overlay_enabled": { desc: "Bake a full-width bar with location and @handle onto every reel and its thumbnail.", recommended: "true (after setting handle)" },
  "branding.ig_handle": { desc: "Your Instagram @handle shown on the bar, e.g. @myaccount. Leave empty to hide the handle (overlay still draws if enabled).", example: "@myaccount" },
  "branding.custom_text": { desc: "Optional second line rendered below the location text (e.g. a tagline or website). Leave empty to hide.", example: "travel.example.com", recommended: "(empty)" },
  "branding.font": { desc: "Font file from assets/fonts/ to use for bar text. Leave empty to use PlayfairDisplay-SemiBold (default).", example: "PlayfairDisplay-SemiBold", recommended: "(empty — PlayfairDisplay)" },
  "branding.font_size": { desc: "Font size in pixels for bar text. 0 = auto (scales proportionally with bar height).", example: "0", recommended: "0 (auto)" },
  "branding.bar_height": { desc: "Bar height in pixels. 45px fits one line; increase to ~70px when using custom_text. Font scales proportionally.", example: "45", recommended: "45" },
  "branding.show_on_thumbnail": { desc: "Apply the same branded bar to the thumbnail image uploaded to R2, so the feed cover matches the video.", recommended: "true" },
  "branding.bar_bg_color": { desc: "Bar background color (CSS hex). Combine with opacity for a translucent look.", example: "#ffffff", recommended: "#ffffff" },
  "branding.text_color": { desc: "Color of location and @handle text (CSS hex).", example: "#000000", recommended: "#000000" },
  "branding.bar_opacity": { desc: "Bar background opacity: 0.0 = fully transparent, 1.0 = fully solid. Text is always opaque.", example: "1.0", recommended: "1.0" },
  "branding.bar_position": { desc: "\"bottom\" places the bar at the foot of the frame; \"top\" places it at the header.", example: "bottom", recommended: "bottom" },
  "branding.location_side": { desc: "Which side of the bar the location text appears on.", example: "left", recommended: "left" },
  "branding.handle_side": { desc: "Which side of the bar the @handle text appears on.", example: "right", recommended: "right" },
  // video
  "video.auto_stabilize": { desc: "Run libvidstab 2-pass stabilization during enhance. Slower (~1–3 min/clip) but smoother footage.", recommended: "false (enable only for shaky footage)" },
  "video.remove_watermarks": { desc: "Blur the Instagram watermark strip during enhance.", recommended: "false" },
  "video.watermark_position": { desc: "Which edge to blur. bottom = footer bar. top = header. both = header + footer.", example: "bottom", recommended: "bottom" },
  // video quality chain (Enh K) — free FFmpeg filters, no GPU
  "video.enhance_quality": { desc: "Master toggle for the free FFmpeg quality chain (denoise + sharpen + higher-quality encode) at the edit stage (Enh K).", recommended: "true" },
  "video.denoise": { desc: "Light hqdn3d denoise before motion/scale so a zoom doesn't amplify grain. Cleans up low-light / compressed archive footage.", recommended: "true" },
  "video.denoise_strength": { desc: "Denoise intensity: light (default) / medium / strong. Stronger softens detail.", example: "light", recommended: "light" },
  "video.sharpen": { desc: "Contrast-adaptive sharpen (cas) applied after the colour LUT — halo-free, cheap.", recommended: "true" },
  "video.sharpen_amount": { desc: "Sharpen strength 0.0–1.0. 0.4 is a safe default; >0.6 can look crunchy.", example: "0.4", recommended: "0.4" },
  "video.crf": { desc: "x264 quality factor. Lower = sharper + bigger file. 20 default; 18 near-lossless, 23 lighter.", example: "20", recommended: "20" },
  "video.preset": { desc: "x264 encode preset. medium balances quality vs the server CPU cap; fast/slow trade speed for size.", example: "medium", recommended: "medium" },
  "video.smooth_motion": { desc: "Motion-compensated frame interpolation (minterpolate). CPU-EXPENSIVE — opt-in; smooths slow-mo / pans.", recommended: "false (very CPU-heavy)" },
  "video.smooth_fps": { desc: "Target frame rate when smooth_motion is on.", example: "60", recommended: "60" },
  // intro screen (v0.9.0)
  "intro.enabled": { desc: "Prepend a splash screen to every reel before publish.", recommended: "true (once configured)" },
  "intro.mode": { desc: "generated = text card; asset = uploaded video/image.", recommended: "generated" },
  "intro.asset_file": { desc: "Filename of uploaded intro asset (when mode = asset)." },
  "intro.duration_s": { desc: "How long the intro screen holds (seconds).", example: "1.5", recommended: "1.5" },
  "intro.animation": { desc: "Overlay animation: none, fade, zoom, slide, blur, wipe, ken_burns, random.", recommended: "fade" },
  "intro.bg_color": { desc: "Overlay color composited over the grabbed video frame.", example: "#000000", recommended: "#000000" },
  "intro.bg_opacity": { desc: "Overlay opacity 0.0–1.0. At 0.20 the grabbed video frame shows through at 80%.", example: "0.20", recommended: "0.20" },
  "intro.text_padding_h": { desc: "Horizontal text padding in px applied to all elements.", example: "40", recommended: "40" },
  // cast screen (v0.9.0)
  "cast.enabled": { desc: "Append a cast/outro screen to every reel before publish.", recommended: "true (once configured)" },
  "cast.mode": { desc: "generated = text card; asset = uploaded video/image.", recommended: "generated" },
  "cast.asset_file": { desc: "Filename of uploaded cast asset (when mode = asset)." },
  "cast.duration_s": { desc: "How long the cast screen holds (seconds).", example: "1.5", recommended: "1.5" },
  "cast.animation": { desc: "Overlay animation: none, fade, zoom, slide, blur, wipe, ken_burns, random.", recommended: "fade" },
  "cast.cta_text": { desc: "Call-to-action line shown on the cast screen.", example: "Follow for more", recommended: "Follow for more" },
  "cast.bg_color": { desc: "Overlay color composited over the grabbed video frame.", example: "#000000", recommended: "#000000" },
  "cast.bg_opacity": { desc: "Overlay opacity 0.0–1.0. At 0.20 the grabbed video frame shows through at 80%.", example: "0.20", recommended: "0.20" },
  "cast.text_padding_h": { desc: "Horizontal text padding in px applied to all elements.", example: "40", recommended: "40" },
  // Intro bottom paddings
  "intro.header_bottom_padding": { desc: "Space below the header element in px.", recommended: "0" },
  "intro.subheader_bottom_padding": { desc: "Space below the sub-header element in px.", recommended: "16" },
  "intro.tags_bottom_padding": { desc: "Space below the tags element in px.", recommended: "0" },
  "intro.category_bottom_padding": { desc: "Space below the category element in px.", recommended: "0" },
  "intro.handle_bottom_padding": { desc: "Space below the handle element in px.", recommended: "0" },
  // merge — multi-clip merge reel (merge_clips.py)
  "merge.enabled": { desc: "Master gate for the multi-clip merge feature. Off = merge endpoints/panel still work on demand, but auto-run never triggers.", recommended: "false (enable when you want merged reels)" },
  "merge.auto_run": { desc: "When the normal create flow runs, build a merged reel from several clips instead of a single clip. Off = single-clip behavior unchanged.", recommended: "false" },
  "merge.clips_per_reel": { desc: "How many clips to stitch into one reel (clamped 2–8). Used when auto_count is off.", example: "4", recommended: "3–4" },
  "merge.auto_count": { desc: "Derive clip count from the target duration; off = use clips_per_reel.", recommended: "true" },
  "merge.target_duration_s": { desc: "Target merged reel length in seconds (clamped 20–45, default 30). Split across clips.", example: "30", recommended: "30" },
  "merge.cut_min_s": { desc: "Minimum per-cut segment length in seconds. Short cuts = rapid montage feel.", example: "1.5", recommended: "1.5" },
  "merge.cut_max_s": { desc: "Maximum per-cut segment length in seconds.", example: "3", recommended: "3" },
  "merge.min_segments": { desc: "Minimum number of cuts/scenes in the montage — auto-count never drops below this (clamped 15–24).", example: "15", recommended: "15" },
  "merge.min_main_videos": { desc: "Best-effort: spread cuts across at least this many source videos (clamped 2–20). A smaller category pool just uses everything it has.", example: "10", recommended: "10" },
  "merge.segments_per_clip": { desc: "Distinct non-overlapping sub-shots pulled from each source video (clamped 1–4); cuts from the same video are interleaved, never back-to-back.", example: "3", recommended: "2–4" },
  "merge.cleanup_segments": { desc: "Delete the per-merge scratch folder of trimmed segments after the final reel renders. Saves disk; the final reel is kept.", recommended: "true" },
  "merge.grade": { desc: "Film-look color grade applied to the whole montage: cinematic_warm, cinematic_cool, moody_dark, bright_clean, vintage_film, high_contrast, neutral, teal_orange, golden_hour, vivid_pop. Empty = off (keep the downstream LUT). When set, the LUT is skipped for merged reels.", example: "cinematic_warm", recommended: "cinematic_warm or empty" },
  "merge.grain": { desc: "Overlay subtle film grain (noise) on the montage for a filmic texture.", recommended: "false" },
  "merge.vignette": { desc: "Darken the frame edges for a cinematic vignette look.", recommended: "false" },
  "merge.selection_strategy": { desc: "How auto-select picks clips: best = highest hook score; diverse = spread across countries; random.", example: "diverse", recommended: "diverse" },
  "merge.scene_aware": { desc: "Use PySceneDetect to pick the best continuous sub-shot of each clip before trimming. Off = trim from the clip start.", recommended: "true" },
  "merge.transition": { desc: "Crossfade transition between clips (fade, dissolve, wipeleft, slideup, …).", example: "fade", recommended: "fade" },
  "merge.transition_ms": { desc: "Crossfade duration in milliseconds (clamped 100–1500). Shorter = snappier cuts.", example: "500", recommended: "400–600" },
  "merge.transition_variety": { desc: "Rotate through a set of transitions between clips instead of a single one.", recommended: "true" },
  "merge.audio_mode": { desc: "\"music\" = one track bed across the reel; \"original\" = keep the first clip's own audio.", example: "music", recommended: "music" },
  "merge.music_fade_s": { desc: "Music fade in/out length in seconds.", example: "1", recommended: "1" },
  "merge.slow_motion": { desc: "Apply slow-motion to alternating clips for a cinematic rhythm.", recommended: "true" },
  "merge.slow_motion_factor": { desc: "Slow-motion speed factor below 1.0 (lower = slower).", example: "0.85", recommended: "0.85" },
  "merge.ken_burns": { desc: "Apply a zoompan pan/zoom to each clip for subtle motion.", recommended: "true" },
  "merge.beat_sync": { desc: "Align cuts to the music's beat grid (librosa). Now on by default; resolves the track before rendering.", recommended: "true" },
  "merge.min_clip_score": { desc: "Reject clips whose blur/shake quality score is below this before merging. 0 = off.", example: "0", recommended: "0" },
  // merge quality enhancement (1.7.0) — CPU-only, uses FFmpeg + OpenCV (already installed)
  "merge.adaptive_fx": { desc: "Per-clip content-adaptive treatment: each clip's screen-time, slow-motion, Ken Burns and denoise/sharpen are decided from its OWN OpenCV metrics — stronger clips hold longer, calm clips get slowed + zoomed, soft clips get sharpened, only noisy clips get denoised. Off = fixed alternating rules for every clip.", recommended: "true" },
  "merge.smart_select": { desc: "Pick the BEST sub-shot of each clip using cheap OpenCV scoring (sharpness + exposure + motion, plus a variety guard) instead of just the longest scene. Near-free; falls back to longest-scene if OpenCV is unavailable.", recommended: "true" },
  "merge.select_sharpness_weight": { desc: "How hard sharpness weighs in the sub-shot aesthetic score (0–1). Higher = prefer crisper moments; lower = balance exposure/motion more.", example: "0.5", recommended: "0.5" },
  "merge.select_min_sharpness": { desc: "Reject sub-shots below this normalized sharpness (0–1) during selection. 0 = off (only rank, never reject).", example: "0", recommended: "0" },
  "merge.color_match": { desc: "Gentle per-segment gray-world white-balance nudge so mixed-source clips don't visibly jump in color cut-to-cut. Subtle by design (±12% max).", recommended: "true" },
  "merge.deband": { desc: "Anti-banding pass after the grade — removes the 8-bit banding grading introduces in skies/gradients. Cheap.", recommended: "true" },
  "merge.hard_cuts_on_beat": { desc: "Mix ~1-frame hard cuts among the crossfades (every 3rd join) for a punchier, more trend-native rhythm instead of every cut being a soft fade.", recommended: "true" },
  "merge.smooth_slowmo": { desc: "Judder-free slow-motion via motion-compensated frame interpolation (minterpolate). Looks much smoother but is CPU-HEAVY (2–5× longer render). Off by default.", recommended: "false (enable per-reel when you want max polish)" },
  "merge.smooth_slowmo_max_s": { desc: "Only interpolate slowed segments up to this length in seconds — caps the extra render cost.", example: "3", recommended: "3" },
  "merge.deblock": { desc: "Remove IG-compression blocking artifacts from each segment before the montage. Cheap.", recommended: "true" },
  "merge.sharpen": { desc: "Per-segment contrast-adaptive sharpen (cas). Off by default because the downstream edit stage already sharpens the final reel — enabling both can over-sharpen.", recommended: "false" },
  "merge.sharpen_amount": { desc: "Sharpen strength (0–1) when merge.sharpen is on.", example: "0.3", recommended: "0.2–0.4" },
  "merge.strong_denoise": { desc: "nlmeans strong denoise for grainy/noisy clips. High quality but CPU-HEAVY. Off by default.", recommended: "false" },
  // merge freshness & variety (1.7.0) — anti-repeat + diversity, metadata-only memory (no cache)
  "merge.dedupe_enabled": { desc: "Avoid repeating clips: a new merged reel from a category you've already posted avoids the exact sub-shots recent reels used, so viewers don't see duplicates. Remembers past cuts from the reel's own metadata (no extra storage). First reel of a category behaves normally.", recommended: "true" },
  "merge.subshot_cooldown_reels": { desc: "Repeat cooldown, in reels: a used sub-shot is hard-blocked from reuse for the last N same-category reels (clamped 0–20). Higher = fresher reels but exhausts a small clip pool faster.", example: "3", recommended: "3" },
  "merge.dedupe_soft_weight": { desc: "How hard to down-weight a clip's sub-shot once it's past the cooldown (0–1). Past the cooldown a used shot is still eligible but its selection score is multiplied by this — lower = avoid harder.", example: "0.5", recommended: "0.5" },
  "merge.proven_topup": { desc: "When the fresh (never-used) pool can't fill the reel, top it up with the highest-scoring previously-used sub-shots instead of falling short. Keeps reels full while staying mostly fresh.", recommended: "true" },
  "merge.proven_min_score": { desc: "Only reuse a previously-used sub-shot for top-up if its aesthetic score is at least this (0–1). Higher = only recycle your genuinely best shots.", example: "0.5", recommended: "0.5" },
  "merge.dynamic_count": { desc: "Auto cut-count + maximum variety: scale the number of cuts to how much footage the category actually has and favor spreading across as many DIFFERENT clips as possible (one cut per clip when the pool allows). Off = fixed min_segments/clips_per_reel.", recommended: "true" },
  "merge.max_cuts_per_source": { desc: "Max cuts taken from a single clip before another clip is reused — the core variety lever. 1 = one cut per clip while distinct clips remain (relaxed automatically on small pools so the reel still fills). 0 = auto.", example: "1", recommended: "1" },
  // decaption — remove burned-in IG captions/watermarks (decaption stage)
  "decaption.enabled": { desc: "Strip burned-in Instagram captions and watermarks from clips before they enter a reel. CPU-heavy (OpenCV inpaint), but each clip is cleaned once then cached and reused, so the cost is paid only the first time.", recommended: "false (enable only if your clips have burned-in text)" },
  "decaption.algorithm": { desc: "OpenCV inpaint method: hybrid (best all-round) | telea (fastest) | ns (Navier-Stokes, best on smooth gradients).", example: "hybrid", recommended: "hybrid" },
  "decaption.detect_mode": { desc: "How the caption region is found: auto (YOLO11 text detection — finds text anywhere) | bottom (bottom third) | top (top third) | custom (fixed box). bottom/top/custom are faster when captions are always in one spot.", example: "auto", recommended: "auto" },
  "decaption.custom_bbox": { desc: "Region to inpaint when detect_mode = custom, as \"x,y,w,h\" in pixels.", example: "0,1600,1080,320" },
  "decaption.min_confidence": { desc: "YOLO11 detection confidence threshold. Higher = fewer false positives but may miss faint text.", example: "0.35", recommended: "0.35" },
  "decaption.dilate_px": { desc: "Expand the detected text mask by this many pixels before inpainting, so anti-aliased edges are fully covered.", example: "6", recommended: "6" },
  "decaption.fallback": { desc: "What to do when inpaint fails on a region: blur (blur the region) | fill (solid fill) | none (keep as-is).", example: "blur", recommended: "blur" },
  // stock — Pexels/Pixabay B-roll sourcing (1.8.0)
  "stock.enabled": { desc: "Search Pexels/Pixabay for stock B-roll and index results as raw media alongside your own archive — merge_clips blends them into the same category montage automatically.", recommended: "false (opt-in; requires a Pexels or Pixabay API key)" },
  "stock.source": { desc: "Which stock provider(s) to search: pexels | pixabay | both.", example: "pexels", recommended: "pexels" },
  "stock.per_category_query": { desc: "Override the built-in search phrase for a category. Empty = built-in cinematic travel phrases per category.", example: "{\"nature\": \"aerial mountain drone\"}", recommended: "(empty)" },
  "stock.max_clips_per_search": { desc: "How many results to fetch per search call.", example: "5", recommended: "5" },
  "stock.min_short_side": { desc: "Reject candidate clips below this short-edge resolution in pixels.", example: "720", recommended: "720" },
  "stock.min_duration_s": { desc: "Reject candidate clips shorter than this many seconds.", example: "5.0", recommended: "5.0" },
  // voiceover — edge-tts narration + burned subtitles (1.8.0)
  "voiceover.enabled": { desc: "Generate a spoken narration of the caption hook line (edge-tts, free) and mux it as the reel's audio, ducking the music bed underneath. Burns word-synced subtitles from the same synthesis pass.", recommended: "false (opt-in; requires backend/scripts DB migration — see Docs)" },
  "voiceover.voice": { desc: "edge-tts voice id.", example: "en-US-AriaNeural", recommended: "en-US-AriaNeural" },
  "voiceover.rate": { desc: "edge-tts speaking-rate adjustment.", example: "+0%", recommended: "+0%" },
  "voiceover.narration_source": { desc: "Where the spoken text comes from: caption_hook (first line of the generated caption) | manual.", example: "caption_hook", recommended: "caption_hook" },
  "voiceover.subtitles_enabled": { desc: "Burn word-synced subtitles from edge-tts's own timestamps (no separate transcription needed).", recommended: "true" },
  "voiceover.subtitle_position": { desc: "Where subtitles render: bottom | top.", example: "bottom", recommended: "bottom" },
  "voiceover.subtitle_font_size": { desc: "Subtitle font size in px.", example: "28", recommended: "28" },
  "voiceover.subtitle_color": { desc: "Subtitle text color (CSS hex).", example: "#ffffff", recommended: "#ffffff" },
  "voiceover.music_duck_volume": { desc: "Music bed volume while a voiceover plays (below the normal ~0.15 default) so narration stays the primary track.", example: "0.08", recommended: "0.08" },
  // Cast bottom paddings
  "cast.cta_bottom_padding": { desc: "Space below the CTA element in px.", recommended: "0" },
  "cast.subheader_bottom_padding": { desc: "Space below the sub-header element in px.", recommended: "16" },
  "cast.tags_bottom_padding": { desc: "Space below the tags element in px.", recommended: "0" },
  "cast.episode_bottom_padding": { desc: "Space below the episode element in px.", recommended: "0" },
  "cast.handle_bottom_padding": { desc: "Space below the handle element in px.", recommended: "0" },
  // editor — timeline reel editor (2.0.0)
  "editor.enabled": { desc: "Master gate for the /editor route and the /api/editor endpoints. Off = the Edit-reel entry point disappears and the API 403s.", recommended: "true" },
  "editor.proxy_height": { desc: "Short-edge px of the low-res proxies the browser player streams. Higher = sharper preview, slower first load and more disk.", example: "480", recommended: "480" },
  "editor.proxy_ttl_days": { desc: "Cached proxies older than this are swept by the nightly job. They are re-cut on demand, so a low value only costs re-encode time.", example: "7", recommended: "7" },
  "editor.autosave_seconds": { desc: "Idle delay before an edit is saved as a new version. Lower = fewer lost edits, more version rows.", example: "15", recommended: "15" },
  "editor.keep_versions": { desc: "Edit-list versions retained per reel; older ones are pruned on save.", example: "20", recommended: "20" },
  "editor.max_text_layers": { desc: "Cap on text overlays per reel — each one is a drawtext filter at render time.", example: "20", recommended: "20" },
  "editor.max_image_layers": { desc: "Cap on image/sticker overlays per reel.", example: "10", recommended: "10" },
  "editor.max_cuts": { desc: "Cap on timeline cuts. Matches the merge stage's own limit; raising it past that will fail at export.", example: "40", recommended: "40" },
  "editor.export_mode": { desc: "overwrite = the existing post is repointed at the exported reel and keeps its slot and caption. new_post = a separate post is created.", example: "overwrite", recommended: "overwrite" },
  "editor.preview_lut": { desc: "Apply the colour grade in the browser preview via a WebGL LUT shader. Off = the player shows ungraded video (the export is unaffected).", recommended: "true" },
};

// Enum string fields → render as a <select> instead of a free-text box so users
// can't type an invalid value. Keyed "<group>.<key>". Empty-string option ("")
// is rendered with the supplied label (e.g. grade "" = off / keep LUT).
export const FIELD_OPTIONS: Record<string, { value: string; label: string }[]> = {
  "pipeline.auto_create_reel_type": [
    { value: "merge", label: "merge — multi-clip cinematic montage" },
    { value: "single", label: "single — one clip" },
  ],
  "editor.export_mode": [
    { value: "overwrite", label: "overwrite — repoint the existing post" },
    { value: "new_post", label: "new_post — create a separate post" },
  ],
  "merge.selection_strategy": [
    { value: "diverse", label: "diverse — spread across the category" },
    { value: "best", label: "best — highest hook score" },
    { value: "random", label: "random" },
  ],
  "merge.audio_mode": [
    { value: "music", label: "music — one licensed bed" },
    { value: "original", label: "original — keep clip audio" },
  ],
  "merge.transition": [
    { value: "fade", label: "fade" },
    { value: "dissolve", label: "dissolve" },
    { value: "wipeleft", label: "wipeleft" },
    { value: "wiperight", label: "wiperight" },
    { value: "slideup", label: "slideup" },
    { value: "slidedown", label: "slidedown" },
    { value: "smoothleft", label: "smoothleft" },
    { value: "smoothright", label: "smoothright" },
    { value: "circleopen", label: "circleopen" },
    { value: "circleclose", label: "circleclose" },
  ],
  "merge.grade": [
    { value: "", label: "off — keep downstream LUT" },
    { value: "cinematic_warm", label: "cinematic_warm" },
    { value: "cinematic_cool", label: "cinematic_cool" },
    { value: "moody_dark", label: "moody_dark" },
    { value: "bright_clean", label: "bright_clean" },
    { value: "vintage_film", label: "vintage_film" },
    { value: "high_contrast", label: "high_contrast" },
    { value: "neutral", label: "neutral" },
    { value: "teal_orange", label: "teal_orange — cinematic split-tone" },
    { value: "golden_hour", label: "golden_hour — warm sunset" },
    { value: "vivid_pop", label: "vivid_pop — punchy & saturated" },
  ],
  "decaption.algorithm": [
    { value: "hybrid", label: "Hybrid (best)" },
    { value: "telea", label: "TELEA (fast)" },
    { value: "ns", label: "Navier-Stokes" },
  ],
  "decaption.detect_mode": [
    { value: "auto", label: "Auto-detect (YOLO)" },
    { value: "bottom", label: "Bottom third" },
    { value: "top", label: "Top third" },
    { value: "custom", label: "Custom box" },
  ],
  "decaption.fallback": [
    { value: "blur", label: "Blur region" },
    { value: "fill", label: "Fill region" },
    { value: "none", label: "Keep as-is" },
  ],
  "stock.source": [
    { value: "pexels", label: "Pexels" },
    { value: "pixabay", label: "Pixabay" },
    { value: "both", label: "Both" },
  ],
  "voiceover.narration_source": [
    { value: "caption_hook", label: "Caption hook line" },
    { value: "manual", label: "Manual" },
  ],
  "voiceover.subtitle_position": [
    { value: "bottom", label: "Bottom" },
    { value: "top", label: "Top" },
  ],
};

export const GROUP_META: Record<string, { label: string; help: string; icon: ElementType; accent: string }> = {
  approval: {
    label: "Approval flow",
    help: "How long previews wait before auto-posting.",
    icon: Clock,
    accent: "blue",
  },
  schedule: {
    label: "Posting schedule",
    help: "Daily slot times and timezone for the scheduler.",
    icon: Clock,
    accent: "purple",
  },
  platforms: {
    label: "Platforms",
    help: "Enable or disable publishing to each platform.",
    icon: Layers,
    accent: "pink",
  },
  ai: {
    label: "AI models",
    help: "Models used for classification, captions, and refinement.",
    icon: Brain,
    accent: "emerald",
  },
  telegram: {
    label: "Telegram bot",
    help: "Webhook vs poll mode, target chat, preview push.",
    icon: MessageCircle,
    accent: "sky",
  },
  music: {
    label: "Music selection",
    help: "Preferred source and IG-licensed-audio swap behavior.",
    icon: Music2,
    accent: "orange",
  },
  taxonomy: {
    label: "Category taxonomy",
    help: "Content categories used by the classifier.",
    icon: Tag,
    accent: "yellow",
  },
  analytics: {
    label: "Analytics",
    help: "How often to ingest Instagram analytics data.",
    icon: BarChart3,
    accent: "teal",
  },
  caption: {
    label: "Caption AI",
    help: "Feedback hooks, trend injection, and self-critique for caption generation.",
    icon: Sparkles,
    accent: "emerald",
  },
  hashtags: {
    label: "Hashtag A/B test",
    help: "Coin-flip between hashtag variants per post to measure reach.",
    icon: Hash,
    accent: "sky",
  },
  vision: {
    label: "Vision scoring",
    help: "Hook-score each video's opening frames with a vision model.",
    icon: Eye,
    accent: "violet",
  },
  selection: {
    label: "Clip selection",
    help: "Blend realized category engagement into which clip gets picked.",
    icon: Target,
    accent: "orange",
  },
  branding: {
    label: "Video branding",
    help: "Burn a white bottom bar with location + @handle onto every reel and thumbnail.",
    icon: AtSign,
    accent: "pink",
  },
  video: {
    label: "Video quality",
    help: "Free FFmpeg enhancement chain: denoise, sharpen, encode quality, stabilize, watermark blur.",
    icon: Film,
    accent: "teal",
  },
  pipeline: {
    label: "System controls",
    help: "Auto-create + auto-publish daemon, pipeline stage toggles, and environment mode.",
    icon: Sliders,
    accent: "red",
  },
  storage: {
    label: "Disk storage",
    help: "Local reels directory size cap and minimum file age before auto-deletion.",
    icon: HardDrive,
    accent: "yellow",
  },
  intro: {
    label: "Intro screen",
    help: "Splash screen prepended to every reel before publish.",
    icon: Clapperboard,
    accent: "indigo",
  },
  cast: {
    label: "Cast screen",
    help: "Outro screen appended to every reel before publish.",
    icon: PlayCircle,
    accent: "violet",
  },
  monetize: {
    label: "Monetize",
    help: "CTA text and link-in-bio injection for caption monetization.",
    icon: DollarSign,
    accent: "yellow",
  },
  merge: {
    label: "Merge reels",
    help: "Stitch several clips into one 30–60s reel with scene-aware cuts and crossfades.",
    icon: Scissors,
    accent: "indigo",
  },
  decaption: {
    label: "Decaption",
    help: "Remove burned-in Instagram captions & watermarks from clips before they enter a reel.",
    icon: Eraser,
    accent: "violet",
  },
  stock: {
    label: "Stock footage",
    help: "Source Pexels/Pixabay B-roll and blend it into merged category reels alongside your archive.",
    icon: Video,
    accent: "sky",
  },
  voiceover: {
    label: "Voiceover",
    help: "edge-tts narration + burned word-synced subtitles.",
    icon: Mic,
    accent: "teal",
  },
  editor: {
    label: "Reel editor",
    help: "Timeline editor: preview proxies, autosave, version history and export caps.",
    icon: Film,
    accent: "indigo",
  },
};

export const GROUP_ORDER: string[] = [
  "pipeline", "platforms", "approval", "ai", "caption", "vision", "hashtags", "monetize", "selection",
  "merge", "video", "editor", "decaption", "stock", "voiceover", "telegram", "music", "taxonomy", "analytics", "storage",
];

export const ACCENT_CLASSES: Record<string, { dot: string; ring: string; icon: string }> = {
  blue:    { dot: "bg-blue-500",    ring: "ring-blue-500/20 bg-blue-500/10",    icon: "text-blue-400" },
  purple:  { dot: "bg-purple-500",  ring: "ring-purple-500/20 bg-purple-500/10", icon: "text-purple-400" },
  pink:    { dot: "bg-pink-500",    ring: "ring-pink-500/20 bg-pink-500/10",    icon: "text-pink-400" },
  emerald: { dot: "bg-emerald-500", ring: "ring-emerald-500/20 bg-emerald-500/10", icon: "text-emerald-400" },
  sky:     { dot: "bg-sky-500",     ring: "ring-sky-500/20 bg-sky-500/10",     icon: "text-sky-400" },
  orange:  { dot: "bg-orange-500",  ring: "ring-orange-500/20 bg-orange-500/10", icon: "text-orange-400" },
  yellow:  { dot: "bg-yellow-500",  ring: "ring-yellow-500/20 bg-yellow-500/10", icon: "text-yellow-400" },
  violet:  { dot: "bg-violet-500",  ring: "ring-violet-500/20 bg-violet-500/10", icon: "text-violet-400" },
  teal:    { dot: "bg-teal-500",    ring: "ring-teal-500/20 bg-teal-500/10",   icon: "text-teal-400" },
  red:     { dot: "bg-red-500",     ring: "ring-red-500/20 bg-red-500/10",     icon: "text-red-400" },
  indigo:  { dot: "bg-indigo-500",  ring: "ring-indigo-500/20 bg-indigo-500/10", icon: "text-indigo-400" },
};
