-- Story-arc reels strategy: per-country mini-series with episode ordering.
-- Replaces hook_score-first selection with chronological series progression.

-- ============================================================
-- 1. series — Per-country mini-series grouping
-- ============================================================
CREATE TABLE IF NOT EXISTS series (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    country TEXT NOT NULL,
    title TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    episode_count INT NOT NULL DEFAULT 0,
    last_published_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'complete')),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_series_country_status ON series(country, status);
CREATE INDEX IF NOT EXISTS idx_series_started ON series(started_at);

-- updated_at trigger mirrors 001:162-168
CREATE TRIGGER series_updated_at
    BEFORE UPDATE ON series
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- RLS mirror of 001:180-205 dual-policy pattern
ALTER TABLE series ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated full access" ON series
    FOR ALL USING (auth.uid() IS NOT NULL);
CREATE POLICY "Service role bypass" ON series
    FOR ALL USING (auth.role() = 'service_role');

-- ============================================================
-- 2. media — episode metadata
-- ============================================================
ALTER TABLE media
    ADD COLUMN IF NOT EXISTS series_id UUID REFERENCES series(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS episode_number INT,
    ADD COLUMN IF NOT EXISTS episode_total INT,
    ADD COLUMN IF NOT EXISTS global_day_number INT,
    ADD COLUMN IF NOT EXISTS series_arc_position TEXT
        CHECK (series_arc_position IS NULL OR series_arc_position IN ('opener','build','climax','closer')),
    -- Per-platform caption variants (generated by caption_gen, copied to posts on enqueue)
    ADD COLUMN IF NOT EXISTS caption_ig TEXT,
    ADD COLUMN IF NOT EXISTS caption_ig_ar TEXT,
    ADD COLUMN IF NOT EXISTS caption_tt TEXT,
    ADD COLUMN IF NOT EXISTS caption_yt_title TEXT,
    ADD COLUMN IF NOT EXISTS caption_yt_description TEXT,
    ADD COLUMN IF NOT EXISTS hashtags_en TEXT[],
    ADD COLUMN IF NOT EXISTS hashtags_ar TEXT[],
    ADD COLUMN IF NOT EXISTS alt_text TEXT;

CREATE INDEX IF NOT EXISTS idx_media_series_episode ON media(series_id, episode_number);
CREATE INDEX IF NOT EXISTS idx_media_global_day ON media(global_day_number);

-- ============================================================
-- 3. posts — per-platform caption columns
-- ============================================================
ALTER TABLE posts
    ADD COLUMN IF NOT EXISTS caption_ig TEXT,
    ADD COLUMN IF NOT EXISTS caption_tt TEXT,
    ADD COLUMN IF NOT EXISTS caption_yt_title TEXT,
    ADD COLUMN IF NOT EXISTS caption_yt_description TEXT;

-- ============================================================
-- 4. analytics — per-platform metrics
-- ============================================================
ALTER TABLE analytics
    ADD COLUMN IF NOT EXISTS platform TEXT NOT NULL DEFAULT 'instagram';

-- UNIQUE(post_id, platform) so 6h ingest job can upsert cleanly.
-- Use DO block because ADD CONSTRAINT IF NOT EXISTS is unsupported.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'analytics_post_platform_unique'
    ) THEN
        ALTER TABLE analytics
            ADD CONSTRAINT analytics_post_platform_unique UNIQUE (post_id, platform);
    END IF;
END$$;
